### ISSUE TITLE
EDA Report location

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_522_Group411#14]
I suggest we move the EDA report (`.md` file and its image files) out of the `src/` folder and into a directory called `reports/` or some appropriate name. The knitted output should be in the `src/` folder.

Thoughts?

**Comment by katieb1** [comment]
Do you think the src folder will get too crowded?

**Comment by techrah** [comment]
Not that it would get too crowded, just that the rendered report doesn't belong in `src/` as it's not a source/script file.

Having said that, I don't think it's anything critical at the moment. We can adjust later.

**Comment by katieb1** [comment]
I noticed that Tiffany includes her EDA.md file in the src, so I think it must be a common practice

**Comment by techrah** [comment]
Ok, let's leave as is. Thanks.
