### ISSUE TITLE
Things to improve

### ISSUE THREAD

**Issue by garyzhubc** [UBC-MDS/DSCI_522_Group411#17]
* Some requirements are not strictly followed: for example, no data table is displayed.
* Very few exploratory analyses are carried out and only some variables are used without explanations.
* Include code in your notebook.

**Comment by andrealee011** [comment]
- we have added data tables in the EDA showing the distribution of variables
- we have conducted additional EDA (added more figures showing the distribution of variables) and have justified why some variables were not used in the EDA
- we have updated the md file to include code
