### ISSUE TITLE
Proposal Discussion

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/DSCI_522_Group411#2]
We can use this issue as a discussion for what we include in our proposal. As specified in milestone1, the proposal should include:

- [x]  A dataset

- [x]  One main predictive or inferential research question

- [x]  A plan for our data analysis (e.g. estimate and CIs, hypothesis test, regression, classification, etc.)

- [x]  At least one relevant EDA table and one relevant EDA figure

- [x]  A plan for how we will share our results with tables and/or figures

**Comment by techrah** [comment]
Based on our "phone" discussion, we will potentially choose from one of the two following datasets:

1. [US accidents](https://www.kaggle.com/mirichoi0218/insurance)
2. [Avocado Prices](https://www.kaggle.com/neuromusic/avocado-prices?fbclid=IwAR35kKP-Fz0yYZj-QqsZ6iNDSVnLBncxTOG3Cce3F5EupQTVHo85ecn7SBo)

**Comment by andrealee011** [comment]
Our potential questions will be:
1. US accidents: predict insurance premiums (based on features (smoker/non, gender, BMI, etc.))
2. Avocado prices: predict avocado prices (based on type (organic/not), region, etc.)

**Comment by katieb1** [comment]
I also found this interesting dataset : https://console.cloud.google.com/marketplace/details/the-world-bank/wdi?filter=solution-type:dataset&filter=category:health&id=8617f452-5015-4bed-b289-890b50f30cbc

It is a dataset of world development indices including features such as 
* Agriculture and Food Security 
* Climate Change
* Economic Growth 
* Education Energy and Extractives 
* Environment and Natural Resources 
* Financial Sector Development 
* Gender 
* Health, Nutrition and Population 

It could be interesting to do some sort of predictive model using this dataset of economic growth of a country based on some of these features! However the dataset is quite large and we'd have to use a query engine to access only a subset of it at a time.

**Comment by techrah** [comment]
> However the dataset is quite large and we'd have to use a query engine to access only a subset of it at a time.

This could be a problem as part of the milestone is to script the downloading of the data.

**Comment by katieb1** [comment]
So now that we have decided to use the avocado dataset, some potential predictive questions we could ask are:
* Do factors, such as region, type (organic vs non-organic), and time of year predict avocado prices?
* Do factors such as bag size, PLU code, type, and region predict how many avocados are sold?

Some inferential questions that we could ask are:
* Does time of year correlate with the average price of avocados?
* Does region correlate with the average price of avocados?
* etc.

What do you guys think? Which questions do you think would be most important to answer?

**Comment by andrealee011** [comment]
More potential questions for the avocado data set:
- What is the price of avocados in US markets?
- What feature most strongly predicts avocado prices?
- How many avocados will be sold next month?

**Comment by andrealee011** [comment]
Question to be confirmed with TA: Given month and region, what is the average price of an avocado?

**Comment by andrealee011** [comment]
Preferred Question (if we learn how to do it): What feature most strongly predicts avocado prices?
Backup Question: Does time of year correlate with average price and volume sold?

**Comment by andrealee011** [comment]
Possible method of analysis to determine feature importance: https://scikit-learn.org/stable/auto_examples/ensemble/plot_forest_importances.html

**Comment by katieb1** [comment]
I'm wondering if we should elaborate on how we will use random forest regression in our analysis? We could just add a few more details on how the model works.

**Comment by andrealee011** [comment]
I’ll add some more details about that to the proposal!

**Comment by techrah** [comment]
See changes in #15
