### ISSUE TITLE
Is multicollinearity appropriate for this dataset?

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_522_Group411#23]
I have attempted to do some analysis on the correlation of the quantitative predictors as well as calculate VIF scores based on an assumed linear model. Linearity was assumed based on a residual plot.

The VIF scores are off the charts. See the [report](https://github.com/UBC-MDS/DSCI_522_Group411/blob/bdc534311b25907bb0fcccf40fb6496c6caac140/src/multicoll/multicoll.md) from PR #22. Values are of the order `e+08` to `e+14`.

Not sure what these results mean.

**Comment by katieb1** [comment]
For some reason I don't see the output of the code chunks in the rendered markdown? It looks like you tested for multicollinearity on the number of avocados sold of each PLU code, the number of bags sold of each size, and the volume sold. I think it makes sense that all of these things are highly correlated (some might even be calculated from adding together components of the other columns). I think it probably just further supports our reasoning for dropping these columns during EDA.

**Comment by andrealee011** [comment]
High VIF scores make sense because all of those features are correlated with each other (ex. total bags sold is very much correlated with total volume sold). We have removed these features from the ML model

**Comment by techrah** [comment]
Thanks for the feedback. Please see #22
