### ISSUE TITLE
ML analysis

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/DSCI_522_Group411#26]
I talked to Mike about our analysis, and I think there are a few issues with the ML analysis so far. 

* **Problem:** we are evaluating month as a discrete categorical variable, when they are actually ordinal/related to one another.   

* **Solution:** turn month into season, and evaluate season as a feature instead.  

* **Problem:** we are evaluating each region as if they are unrelated, but some regions are closer to one another than others.

* **Solution**: turn region into lat/long and evaluate as a numerical variable.

I know this creates a bit more work for us, as the features in the hypothesis tests and multicollinearity tests will need to be modified, but I think it may fix the issues we've been having with the weird random forest results.

What do you guys think?

**Comment by techrah** [comment]
Wow. Very interesting take on feature engineering. It would be interesting to implement these features and see how it affects the modelling.

I think we should run this by Tiffany or Firas. We're supposed to get the entire pipeline into place and then iterate on the analysis in subsequent milestones. However, I realize that this means having to write up an analysis now and then redo it in the next milestone.

How about this. Let's try to complete script 5 and finish off the milestone requirements. The `.Rmd` file can have placeholder text for now. Afterwards, if we do not have enough time, we fill in the placeholder text with the results we have for now and state that we will improve based on the the solutions above. If we have enough time, we can work on the modifications for this milestone.

**Comment by katieb1** [comment]
Okay, I am going to make the script with just the analysis that I have so far and then we can fix the model later if we have time.

**Comment by andrealee011** [comment]
this has been added into the discussion/critique section of the report (on how to improve our model)

**Comment by techrah** [comment]
This was handled in #43, #45 and #46.

**Comment by katieb1** [comment]
I'm going to close this issue now, since we fixed it for the next version release.
