### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by andrealee011** [UBC-MDS/DSCI_522_Group411#40]
1. residual plot: be more clear linear model was used, plot mean line
2. EDA region plot is a bit cluttered but don't know how else to show it
3. be more clear why we chose features we chose (specify at the top of analysis section to  say that we will explain later)
4. show only top view of long p-value table

**Comment by andrealee011** [comment]
Solutions:
1. will add linear model in the title
2. will leave plot as is for now
3. this will be more clear when we move hypothesis and multicollinearity test to EDA section
4. when data is fixed (region converted to lat and lon, and month changed to numerical) p-value table will not be long

**Comment by katieb1** [comment]
addressed in plan for milestone 3 (issue #42)
