### ISSUE TITLE
Visualization Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_Group411#57]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [ ] THANK YOU (!!) for having a table at the beginning that has a human-readable version of the column/feature names
- - [ ] Great job adding figure numbers and captions! Though your captions could have been a bit more informative, overall this is a very good practice. 
- - [ ] Figure 1A:
	- - [ ] Also, you have five figures listed under "figure 1" - is this intentional?
	- - [ ] Definitely switch x and y so categorical axes are on the y-axis and it's easier to read
	- - [ ] It looks like you sorted by price, which is great!
- - [ ] Figure "1B" and "1C":
	- - [ ] There is lots of interesting information in this plot, but there is also some severe over-plotting. I see that you have the mean value shown on the plot, which is great and really makes this plot stand out
	- - [ ] Have you considered other ways of showing this information? How about a ridgeline plot?
- - [ ] Figure "1D" and "1E":
	- - [ ] This is a good plot!
	- - [ ] It takes a lot of space though, so you should arrange it so that it's a multi-paned. See [this link](https://ubc-mds.slack.com/archives/C24HUNRJL/p1579556279096800?thread_ts=1579546321.094500) for links and suggestions on how to do this
- - [ ] Figure 2:
	- - [ ] Looks good! 
	- - [ ] Maybe reduce the size of this figure a bit so it takes up less space
- - [ ] All tables:
	- - [ ] Too many sig figs, there's no need to show that many, it hurts readability and interpretability
- - [ ] Figure 3:
	- - [ ] This is really good and effective!
- - [ ] Figure 4:
	- - [ ] Definitely switch x and y so categorical axes are on the y-axis and it's easier to read
	- - [ ] Use your human-readable names for the features since you already have them
	- - [ ] I like how this graph summarizes everything and how you sorted the features by importance, nice work!
- - [ ] Overall the report looks very polished and clean! Great work! Excellent work with your labels, titles, and plot choices! For every plot I was immediately able to understand what you were trying to convey.

**Comment by katieb1** [comment]
addressed in issue #58
